name: Toggle PR With Issue

on:
    types: [closed, reopened]

jobs:
  start:
    steps:
      - uses: actions/checkout@v2
      - run: cd scripts && npm i --only=production
      - run: cd scripts/actions && npx esno ./loader.ts ${{github.token}} toggle-pr-with-issue
